spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth-db # Temporary
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

jwe:
  issuer: "JM_BACKEND"
  # Paste the content of public_key.pem
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4d88Wf9iU46t1Rn9V44z
    kIQ+6uZLRhl9evNN7cR9l/5if2nfOamJwjaM7JgnVkLclsu/dcT0wO8wli2l4Ooe
    pXYM3djePpqpkdGCqZkEfrU+JKu0mz/ed4p7Y/KzpBRJcLDIGmxcZQso4T/uUPBR
    WzBbqEA81GSfw3ZJeD5H9aeKbrnZKhEdKoNRSM/eBNAgVQIsDI7HpfJMzku7KfsI
    8RV47PvlFu0i5YAtwT9QTtEUnr/I8eAYSQXmVrs/lEe4MNFLbyN3+vmfTKuE7A5V
    RsgpyiPm0ylDXQpCXQ8LWuN+HvjFKQlVdq0qmVkCpLDv2P3fHU7aoYwg3/IcJps3
    0wIDAQAB
    -----END PUBLIC KEY-----


  # Paste the content of private_key.pem
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDh3zxZ/2JTjq3V
    Gf1XjjOQhD7q5ktGGX16803txH2X/mJ/ad85qYnCNozsmCdWQtyWy791xPTA7zCW
    LaXg6h6ldgzd2N4+mqmR0YKpmQR+tT4kq7SbP953intj8rOkFElwsMgabFxlCyjh
    P+5Q8FFbMFuoQDzUZJ/Ddkl4Pkf1p4puudkqER0qg1FIz94E0CBVAiwMjsel8kzO
    S7sp+wjxFXjs++UW7SLlgC3BP1BO0RSev8jx4BhJBeZWuz+UR7gw0UtvI3f6+Z9M
    q4TsDlVGyCnKI+bTKUNdCkJdDwta434e+MUpCVV2rSqZWQKksO/Y/d8dTtqhjCDf
    8hwmmzfTAgMBAAECggEAGRFnB8/9sCtaJJgFU3XPSD89ImHbwdRrZj1hjT1s+PT9
    JonwAdzMkrbuLgX2+65hAAVt4tqwlUcWm9xGGC+zpgZziB2dENKmdi4L89mtM4jW
    9EfwO/i7LoY6io2xnUi5G94q3y/ek0JJT7KCNw5s4RN9YK98cNAYIR/cKJG099Di
    btcsG6uT1v88Fg0aEkMlmqfyFZMAlboHqkk7bLJtn9HcCxzSr0yoXew7O0+cBb9i
    +uXTLfMWo3Vf5ofSHeP1bzMZtQofb5R//eWUF/Pm3hs20/u06PpfrnjbIAK4uJVW
    OL48PIQvX2Zgfsark/NCe6YCoOomKO8aRSn7mbJLqQKBgQD8R4Hv66pUy1omS1m8
    uAiD3NpzSjPP3afZcmtM8bGsjccEAqf2YpDwtmlUPy4AlniQqTOhrATGshLDR3WI
    dhN8Q3STZ5y7OpDNf7Gq0xvC3lXy4p7x1OZgGf1Rlygr/vMVMA8w+b7viQ4BTDK5
    xjC5UgQY+GYa692MlGW3hNnLWQKBgQDlNAaw4eqyq6zDichGGjZubAc+pSOvw0V0
    4PmWpTBgudZIrLQzi0qplZzNGZNVDq91tleDwk0fam0Pz4YsDNT/ye+YnJ+oOZwr
    GORP6nQVNvCSRFSnZYRh4smWzGsmRNSqHSls8xuXTjoHUGG8fBAG+vcW3pPIT/Ab
    hwDrKcrzCwKBgQCLEmBvAltDo1ZvBdrSTiFjj7xdEeq+DFMbbBf6ssJffUjYzR4K
    lQuRpv0plCqn6EtOc/gih9GaN1BglmQUdgMH3afGGrgr/n0Uy/AFW5tSMX7wBj3Y
    0qStFaav88QRfNpEM9osBYFcSxGNZZQRFVCG2M+pdEXVUXEwrh3krTfjAQKBgGPx
    UK2WhUGNjFLjZJn02iFCJ9KQLcR5cHLrmsmulC7JOgAMlrMXHOJfo7TnXxAqzCWW
    8gg5FGoLfSz0v7u7iLFUu44fVZsEK+269+tE/4M0pqgQ9ZzcrmIEgwSndF2Gi/j1
    qFeiljhe2vzPdx66Nj7k9hNZ0LT67mcCcksYuS9LAoGAedGpitcSzJzQDQ0MXAmu
    PIX7Av+a1MQQGUNqEUqOSyqgb6dE9Gy3ojDZ8RE9YwgZjfVgs6VCcuT2uACg8ksr
    71CYD2YJvrG6EJxydcPOWM5RjegQGIVNan+JzxPMj1GNVVciExy95ZfoSemzBPEb
    s1352Y9sXWSIhexIxZGKyD8=
    -----END PRIVATE KEY-----
